---
title: "Taxonomic resolution using LCP and lcplants"
author: "Alexander Zizka"
output: html_document
---

# Background

# The Leipzig Plant Catalogue

# Using lcplants

#' # To submit one single plant taxa name or a list:
#' LCP("Hibiscus vitifolius")
#' # To submit a plant taxa name to solve some possible orthographic errors:
#' LCP("Hibiscus vitfolius", max.distance = 1)
#' # To submit a plant taxa name to solve possible orthographic errors also at the genus level:
#' LCP("Hibiescus vitifolius", max.distance = 1, genus_search = TRUE)
#' # To submit a plant taxon looking for all the synonym names:
#' LCP("Hibiscus vitifolius", status = FALSE)
#' # To submit a plant taxa name looking for all infraspecies names:
#' LCP("Hibiscus vitifolius", infraspecies_tab = TRUE)
#' # To submit a plant taxa name looking for all plant taxa names belonging to the same genus rank:
#' LCP("Hibiscus", genus_tab = TRUE)
#' # To execute the searching process booking a fixed number of
#' # CPU cores available on the working machine:
#' LCP("Hibiscus vitifolius", max.cores = 3)
#' # To save the result to a Comma-Separated Values (.csv) file:
#' LCP("Hibiscus vitifolius", save = TRUE)